## Матрицы и матричные операции. Часть 1

**1.** Установите, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найдите размерности полученных матриц: <br>

**Решение**
* 𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2. Число столбцов первой матрицы не равно числу строк второй матрицы. Произведения не существует.
* 𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3.  Число столбцов первой матрицы  равно числу строк второй матрицы, значить произведение матриц существует. Матрица произведения имеет размерность 2х3. 
* 𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8. Число столбцов первой матрицы  равно числу строк второй матрицы, значить произведение матриц существует. Матрица произведения имеет размерность 8х8. 
* 𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4.  Число столбцов первой матрицы  равно числу строк второй матрицы, значить произведение матриц существует. Матрица произведения имеет размерность 4х4. 

**2.** Найдите сумму и произведение матриц: $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

**Решение**
* $A+B=\begin{pmatrix}
1+4 & -2-1\\
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}$

* $A\cdot{}B=
\begin{pmatrix}
1\cdot4-2\cdot0 & -1\cdot1-2\cdot5\\
3\cdot4+0\cdot{}0 & -3\cdot1+ 0\cdot5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\
12 &  -3
\end{pmatrix}$

**3.** Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

**Решение** <br>
$3A-2B+4C = 
3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} =
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}  + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}  .$

**4.** Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

**Решение** <br>
$AA^{T}=
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot
\begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3\\ 
\end{pmatrix}=
\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5-2\cdot1 & 4\cdot2+1\cdot3\\ 
5\cdot4-2\cdot1 & 5\cdot5+2\cdot2 & 5\cdot2 -2\cdot3\\ 
2\cdot4 + 3\cdot1 & 2\cdot5-3\cdot2 & 2\cdot2+3\cdot3
\end{pmatrix}=
\begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4\\ 
11 & 4 & 13\\ 
\end{pmatrix}
$ 

$A^{T}\cdot{}A=
\begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3\\ 
\end{pmatrix}\cdot{}
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=
\begin{pmatrix}
4\cdot4 +5\cdot5+2\cdot2 & 4\cdot1-5\cdot2+2\cdot3 \\ 
1\cdot4 -2\cdot5+3\cdot2 & 1\cdot1+2\cdot2+3\cdot3 
\end{pmatrix}=
\begin{pmatrix}
45 & 0  \\ 
0 & 14 
\end{pmatrix}
$

**5.** Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.




In [1]:
def matrix_mult(a,b):
    assert (len(a[0]) == len(b)), 'Число столбцов первой матрицы должно совпадать с числом строк второй матрицы'
    out = []
    for y in range(len(a)):
        temporows = []
        for x in range(len(b[0])):
            tempo = 0 
            for ind in range(len(a[0])):
                tempo+=a[y][ind]*b[ind][x]
                #print(a[y)
            temporows.append(tempo)
        out.append(temporows)
    return out  
    
A= [[1,3,5,-5], [10,15,50,0], [2,1,19,-120]]
B= [[9,15,7], [1,18,52], [19,10,5], [-100,321,519]]
print(f'Произведение матриц =>{matrix_mult(A,B)}')

print('Проверка с помощью numpy')
import numpy as np
print(np.dot(A,B))    

Произведение матриц =>[[607, -1486, -2407], [1055, 920, 1100], [12380, -38282, -62119]]
Проверка с помощью numpy
[[   607  -1486  -2407]
 [  1055    920   1100]
 [ 12380 -38282 -62119]]


## Матрицы и матричные операции. Часть 2

__1.__ Вычислите определитель:

* $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=
sinx\cdot{}sinx+cosx\cdot{}cosx
$
* $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot5\cdot9=180$. Для треугольной матрицы определитель равен произведению элементов главной диагонали.
* $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=\begin{vmatrix}
1 & 2 & 3\\ 
4 -1 & 5-2 & 6-3\\ 
7-4 & 8-5 & 9-6
\end{vmatrix}=\begin{vmatrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
3 & 3 & 3
\end{vmatrix}=\begin{vmatrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
0 & 0 & 0
\end{vmatrix} = 0
$

**2.** Определитель матрицы $A$ равен $4$. Найдите:  $det(A^{2})$;  $det(A^{T})$; $det(2A)$.

**Решение** 
* $det(A^{2})= det(A)\cdot  det(A)=16 $;
* $det(A^{T}) = det(A) = 4$
* $det(2A)$. Определитель посчитать невозможно, так как необходимо знать порядок матрицы

**3.** Докажите, что матрица:

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$ вырожденная.

**Решение** <br>
$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}$=
$\begin{vmatrix}
-4 & 14 & -6\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}$=$\begin{vmatrix}
0 & 0 & 0\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}$ <br>
Определитель равен нулю. Поэтому матрица вырожденная.

**4.**  Найдите ранг матрицы:

 $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**Решение**
* $\begin{vmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{vmatrix}$=
 $\begin{vmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 0 & 0
\end{vmatrix}=0$ <br>
Третья строка является линейной комбинацией первых двух. Значит матрица вырожденная. Вместе с тем определитель второго порядка 
не равен нулю. Значит ранг равен двум.

* $\begin{vmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{vmatrix}.$ =  $\begin{vmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{vmatrix}.$ =  $\begin{vmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
3 & 5 & 6
\end{vmatrix}.$=6 <br>
Определитель матрицы третьего порядка  не равен нулю. Значит ранг равен трем.